### ISSUE TITLE
Problem inserting images in JSFiddle

### ISSUE THREAD

**Issue by Savinss** [wbigger/book-html5#1]
Prof, ho dei piccoli problemi nell'inserire le immagini nel Fiddle

**Comment by wbigger** [comment]
Puoi descrivere meglio? Che problemi?

**Comment by Savinss** [comment]
Li ho risolti prof, devi mettere il link anche nel css del lavoro completo??

Il giorno Ven 30 Nov 2018, 12:59 Claudio Capobianco <
notifications@github.com> ha scritto:

**Comment by wbigger** [comment]
Sì grazie! Sono due fiddle diversi ovviamente: uno con il solo HTML, e
l'altro con anche il CSS.

**Comment by Savinss** [comment]
Perfetto finisco subito il lavoro prof, buona giornata!

Il giorno Ven 30 Nov 2018, 13:07 Claudio Capobianco <
notifications@github.com> ha scritto:

> Sì grazie! Sono due fiddle diversi ovviamente: uno con il solo HTML, e
> l'altro con anche il CSS.
>
>
>

**Comment by Savinss** [comment]
Ho inviato la pull requestsprof, le è arrivata??

Il giorno Ven 30 Nov 2018, 13:07 Claudio Capobianco <
notifications@github.com> ha scritto:

> Sì grazie! Sono due fiddle diversi ovviamente: uno con il solo HTML, e
> l'altro con anche il CSS.
>
>
>

**Comment by wbigger** [comment]
Arrivata e fatto il merge 👍
